apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: wp
namePrefix: tenanta-
commonLabels: 
  tenant: tenantA

images:
  - name: wordpress
    newName: wordpress
    newTag: latest

patchesStrategicMerge:
  - kust-deployment.yaml

patchesJson6902:
  - target:
      group: mysql.presslabs.org
      version: v1alpha1
      kind: MysqlCluster
      name: wordpress-mysql-cluster
    patch: |-
      - op: replace
        path: /spec/secretName
        value: tenanta-wordpress-mysql-secret
  - target:
      group: mysql.presslabs.org
      version: v1alpha1
      kind: MysqlDatabase
      name: wordpress-mysql-database
    patch: |-
      - op: replace
        path: /spec/clusterRef/name
        value: tenanta-wordpress-mysql-cluster
  - target:
      group: mysql.presslabs.org
      version: v1alpha1
      kind: MysqlUser
      name: wordpress-mysql-user
    patch: |-
      - op: replace
        path: /spec/clusterRef/name
        value: tenanta-wordpress-mysql-cluster
      - op: replace
        path: /spec/user
        value: wordpress
      - op: replace
        path: /spec/password/name
        value: tenanta-wordpress-db-pwd
      - op: replace
        path: /spec/permissions/0/schema
        value: wordpress-db
  - target: 
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: wpdb-netpol-deny-all
    patch: |-
      - op: add
        path: /spec/podSelector/matchLabels
        value: 
          app.kubernetes.io/component: database
          mysql.presslabs.org/cluster: tenanta-wordpress-mysql-cluster
          statefulset.kubernetes.io/pod-name: tenanta-wordpress-mysql-cluster-mysql-0
          tenant: tenantA
  - target: 
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: db-netpol-allow-ingress-3306-wp-pod
    patch: |-
      - op: add
        path: /spec/podSelector/matchLabels
        value: 
          app.kubernetes.io/component: database
          mysql.presslabs.org/cluster: tenanta-wordpress-mysql-cluster
          statefulset.kubernetes.io/pod-name: tenanta-wordpress-mysql-cluster-mysql-0
          tenant: tenantA
  - target: 
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: wpapp-netpol-deny-egress
    patch: |-
      - op: add
        path: /spec/podSelector/matchLabels
        value: 
          name: wordpress-pod
          tenant: tenantA
  - target: 
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: app-netpol-allow-egress-3306-db-pod
    patch: |-
      - op: add
        path: /spec/podSelector/matchLabels
        value: 
          name: wordpress-pod
          tenant: tenantA
      - op: add
        path: /spec/egress/0/to/0/podSelector/matchLabels
        value:
          app.kubernetes.io/component: database
          mysql.presslabs.org/cluster: tenanta-wordpress-mysql-cluster
          statefulset.kubernetes.io/pod-name: tenanta-wordpress-mysql-cluster-mysql-0
replacements:
  - source: 
      kind: Service
      name: wordpress-svc
      fieldPath: metadata.name
      options:
        delimiter: '-'
        index: 0
    targets:
    - select:
        kind: Ingress
        name: wordpress-ing
      fieldPaths: 
      - spec.rules.0.host
      options:
        delimiter: '-'
        index: 0