apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  template:
    spec:
      containers:
      - name: wordpress-container
        env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: PASSWORD
                name: tenanta-wordpress-db-pwd
          - name: WORDPRESS_DB_USER
            valueFrom: 
              configMapKeyRef: 
                key: USER
                name: tenanta-wordpress-db-conn
          - name: WORDPRESS_DB_NAME
            valueFrom: 
              configMapKeyRef: 
                key: DB
                name: tenanta-wordpress-db-conn
        volumeMounts:
          - name: tenanta-wordpress-volume
            mountPath: /var/www/html
      volumes: 
        - name: tenanta-wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc