apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  labels:
    name: dov-pod
    dept: engg
  namespace: myns
spec:
  containers:
    - name: dov-container
      image: enghuat91/dov-bear:java-v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          value: "5000"
        - name: INSTANCE_NAME
          value: "dov-pod"
        - name: INSTANCE_HASH
          value: "9f1eb20caebd5e256a9a05d720ed3e1c"