apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: myns2
namePrefix: v1-
commonLabels: 
  deployDate: "31032022"
  version: v1

patchesStrategicMerge:
- kust-deployment.yaml
- kust-hpa.yaml

images:
  - name: bgg-backend
    newName: stackupiss/bgg-backend
    newTag: v1

replicas: 
  - name: bggapp-deploy
    count: 1