volumes:
  my-data:

networks:
  app-net:

services:
  nwdb:
    image: stackupiss/northwind-db:v1
    volumes:
      - my-data:/var/lib/mysql
    networks:
      - app-net
  nwApp:
    image: stackupiss/northwind-app:v1
    networks:
      - app-net
    ports:
      - 8080-8090:3000
    environment:
      - DB_HOST=nwdb
      - DB_USER=root
      - DB_PASSWORD=changit
      