apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../workshop02/class-demo/

namespace: myns
namePrefix: kuz-
nameSuffix: -k8s
commonLabels: 
  deployDate: "31032022"

replicas: 
  - name: dov-deploy
    count: 5