apiVersion: v1
kind: Secret
metadata:
  name: bggapp-db-secret
  labels:
    name: bggapp-db-secret
data:
  BGG_DB_USER: "cm9vdA=="
  BGG_DB_PASSWORD: "Y2hhbmdlaXQ="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-db-cm
  labels:
    name: bggapp-db-cm
data:
  BGG_DB_HOST: "mydb-svc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
  namespace: myns
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: bggapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
      namespace: myns
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # container port
          envFrom:
            - configMapRef:
                name: bggapp-db-cm
            - secretRef:
                name: bggapp-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: NodePort
  selector:
    name: bggapp-pod
  ports:
    - port: 8080 # service port
      targetPort: 3000 # container port